# docker-compose.yml
services:
  ros:
    build: .
    image: cs2-jazzy-base:dev
    container_name: cs2
    # network_mode: "host"
    # privileged: true
    ports:
      - "8080:8080"        # NiceGUI
      - "22223:22223"      # QTM v1.1+ (Little Endian) - MAIN PORT
      - "22222:22222"      # QTM v1.0 (Legacy) - FALLBACK
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
      # Cfirmware setup for SIL drone sim
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      # ---------------------------------
    privileged: true
    volumes:
      - ./ros2_ws:/ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb
    # devices:
      # - "dev/bus/usb:/dev/bus/usb"
      # - /dev/input:/dev/input

    stdin_open: true
    tty: true
